### ISSUE TITLE
Split normalize_config into two functions

### ISSUE THREAD

**Issue by Macr0Nerd** [carsdotcom/cars-forge#12]
# The Issue
In `src/forge/common.py` there is a function `normalize_config`. It is used to normalize the configuration values, but it currently does too many things.

# The Solution
Separate `normalize_config` into `parse_additional_config` and `normalize_config` where `parse_additional_config` will handle the extra functionality in processing the additional config. Replace the function calls to `normalize_config` where it calls the additional config part of the function.

# Notes
The additional config part of `normalize_config` is called in `main.py` around line 140 and in `yaml_loader.py` around 230.

**Comment by donheshanthaka** [comment]
Hey there, can you assign me to this task? i have already started working on it. :)

**Comment by jagmoreira** [comment]
Closed by #27
