### ISSUE TITLE
Add multi-AZ support using placement score

### ISSUE THREAD

**Issue by npatel-cars** [carsdotcom/cars-forge#3]
**Problem:**
Currently, Forge uses only one availability zones (AZ). We want to be able to provide multiple AZs and utilize placement scores to find the best one.

**Goal:**
Allow Forge to handle multiple AZs.
Implement Placement Scores 

**How can you help?**
- Create a PR that adds multi-AZ functionality or placement scores.
- Link the PR to this issue so the work can be properly tracked.

**Comment by jagmoreira** [comment]
Added in #41
